---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: generate znc makepass
  expect:
    command: znc --makepass
    responses:
      (?i)password: "{{ znc_conf_user_password }}"
    creates: /var/lib/znc/.znc/configs/znc.conf
  register: znc_makepass

- name: register znc pass method
  shell: >
    echo "{{ znc_makepass.stdout }}" | grep -oP "(?<=Method = ).+"
  register: znc_conf_user_pass_method
  when: znc_makepass.changed

- name: register znc pass hash
  shell: >
    echo "{{ znc_makepass.stdout }}" | grep -oP "(?<=Hash = ).+"
  register: znc_conf_user_pass_hash
  when: znc_makepass.changed

- name: register znc pass salt
  shell: >
    echo "{{ znc_makepass.stdout }}" | grep -oP "(?<=Salt = ).+"
  register: znc_conf_user_pass_salt
  when: znc_makepass.changed

- name: create znc datadir
  file: path=/var/lib/znc/.znc/configs state=directory mode=0700
  become: yes
  become_user: znc

- name: copy znc conf
  template: src=znc.conf.j2 dest=/var/lib/znc/.znc/configs/znc.conf mode=0600
  become: yes
  become_user: znc
  when: znc_conf_use_template and znc_makepass.changed
  notify: restart znc

- name: generate znc pemfile
  command: znc --makepem creates=/var/lib/znc/.znc/znc.pem
  become: yes
  become_user: znc
  notify: restart znc

- name: start and enable znc
  service: name=znc state=started enabled=yes
